// Demo/test topology (M38): the 49 devices of infra/seed/devices.csv (sample AP left out) plus the
// two APs the prototype scenarios use. Fixed on purpose — scenarios and their expected results must
// not move when the live registry changes. Regenerate by hand only together with scenarios.ts.
import type { TopologyDevice } from '../status.js';

export const DEMO_TOPOLOGY: TopologyDevice[] = [
  { code: 'c2116', name: 'CCR2116', role: 'core', uplink: null },
  { code: 'c1036', name: 'CCR1036', role: 'core', uplink: 'c2116' },
  { code: 'mainA', name: 'MainA', role: 'core', uplink: 'c2116' },
  { code: 'udm', name: 'UDM Pro Max', role: 'controller', uplink: 'c2116' },
  { code: 'omada', name: 'Omada Fusion 2.5G', role: 'controller', uplink: 'c2116' },
  { code: 'wan0', name: 'NT', role: 'wan', uplink: 'c2116' },
  { code: 'wan1', name: '3BB', role: 'wan', uplink: 'c2116' },
  { code: 'wan2', name: 'TRUE', role: 'wan', uplink: 'c2116' },
  { code: 'wan3', name: 'AIS', role: 'wan', uplink: 'c2116' },
  { code: 'm-sp', name: 'อาคารกีฬา main', role: 'main', uplink: 'm-i2' },
  { code: 'm-sp3', name: 'อาคารกีฬา ชั้น 3 (ไฟเบอร์)', role: 'main', uplink: 'c1036' },
  { code: 'sw-sp-1', name: 'อาคารกีฬา ชั้น 1', role: 'access', uplink: 'm-sp' },
  { code: 'm-i2', name: 'ICET2 main', role: 'main', uplink: 'c1036' },
  { code: 'sw-i2-2', name: 'ICET2 ชั้น 2', role: 'access', uplink: 'm-i2' },
  { code: 'sw-i2-3', name: 'ICET2 ชั้น 3', role: 'access', uplink: 'm-i2' },
  { code: 'sw-i2-4', name: 'ICET2 ชั้น 4', role: 'access', uplink: 'm-i2' },
  { code: 'sw-i2-5', name: 'ICET2 ชั้น 5', role: 'access', uplink: 'm-i2' },
  { code: 'sw-i2-6', name: 'ICET2 ชั้น 6', role: 'access', uplink: 'm-i2' },
  { code: 'sw-i2-7', name: 'ICET2 ชั้น 7', role: 'access', uplink: 'm-i2' },
  { code: 'm-i1', name: 'ICET1 main ชั้น 1 (มุมฝั่ง ICET2)', role: 'main', uplink: 'c1036' },
  { code: 'sw-i1-1', name: 'ICET1 ชั้น 1', role: 'access', uplink: 'm-i1' },
  { code: 'm-i1w', name: 'ICET1 main ชั้น 1 (ฝั่งอาคารกีฬา)', role: 'main', uplink: 'm-b1' },
  { code: 'm-b1', name: 'อาคาร 1 main', role: 'main', uplink: 'c1036' },
  { code: 'sw-b1-2', name: 'อาคาร 1 ชั้น 2', role: 'access', uplink: 'm-b1' },
  { code: 'm-b2', name: 'อาคาร 2 main', role: 'main', uplink: 'c1036' },
  { code: 'sw-b2-2', name: 'อาคาร 2 ชั้น 2', role: 'access', uplink: 'm-b2' },
  { code: 'm-s8', name: '8 เซียน main', role: 'main', uplink: 'c1036' },
  { code: 'sw-s8-a', name: '8 เซียน ชั้น 3 (24 port)', role: 'access', uplink: 'm-s8' },
  { code: 'sw-s8-b', name: '8 เซียน ชั้น 3 (16 port)', role: 'access', uplink: 'm-s8' },
  { code: 'fin', name: 'การเงิน', role: 'access', uplink: 'm-s8' },
  { code: 'm-a1', name: 'อาคาร A main ชั้น 1', role: 'main', uplink: 'mainA' },
  { code: 'mainB', name: 'MainB', role: 'main', uplink: 'mainA' },
  { code: 'm-a4', name: 'อาคาร A main ชั้น 4', role: 'main', uplink: 'mainB' },
  { code: 'sw-bb-2', name: 'อาคาร B ชั้น 2', role: 'access', uplink: 'mainB' },
  { code: 'sw-bb-4', name: 'อาคาร B ชั้น 4', role: 'access', uplink: 'mainB' },
  { code: 'sw-bb-6', name: 'อาคาร B ชั้น 6', role: 'access', uplink: 'mainB' },
  { code: 'nvr-b2-0', name: 'NVR อาคาร 2 #1', role: 'nvr', uplink: null },
  { code: 'nvr-b2-1', name: 'NVR อาคาร 2 #2', role: 'nvr', uplink: null },
  { code: 'nvr-b2-2', name: 'NVR อาคาร 2 #3', role: 'nvr', uplink: null },
  { code: 'nvr-b2-3', name: 'NVR อาคาร 2 #4', role: 'nvr', uplink: null },
  { code: 'nvr-i1-0', name: 'NVR ICET1 #1', role: 'nvr', uplink: null },
  { code: 'nvr-i1-1', name: 'NVR ICET1 #2', role: 'nvr', uplink: null },
  { code: 'nvr-i1-2', name: 'NVR ICET1 #3', role: 'nvr', uplink: null },
  { code: 'nvr-sp-0', name: 'NVR อาคารกีฬา #1', role: 'nvr', uplink: null },
  { code: 'nvr-sp-1', name: 'NVR อาคารกีฬา #2', role: 'nvr', uplink: null },
  { code: 'nvr-s8-0', name: 'NVR 8 เซียน #1', role: 'nvr', uplink: null },
  { code: 'nvr-ba-0', name: 'NVR อาคาร A #1', role: 'nvr', uplink: null },
  { code: 'nvr-bb-0', name: 'NVR อาคาร B #1', role: 'nvr', uplink: null },
  { code: 'nvr-i2-0', name: 'NVR ICET2 #1', role: 'nvr', uplink: null },
  { code: 'ap-s8-6-1', name: 'AP 8 เซียน ชั้น 6 #1', role: 'ap', uplink: 'sw-s8-b' },
  { code: 'ap-ba-5-2', name: 'AP อาคาร A ชั้น 5 #2', role: 'ap', uplink: 'm-a4' },
];
