// GENERATED by `pnpm db:pull` (drizzle-kit pull) from a database migrated with migrations/*.sql.
// Do not edit by hand — change the SQL migration, migrate a scratch DB, then re-run db:pull (ADR-0018).
import { relations } from 'drizzle-orm/relations';
import {
  organizationsInCore,
  contactsInCore,
  sitesInCore,
  buildingsInCore,
  buildingFormsInCore,
  floorsInCore,
  locationsInCore,
  locationTypesInCore,
  sourceSystemsInCore,
  staffInCore,
  externalRefsInCore,
  attachmentsInCore,
  calendarEventsInCore,
  modelsInCatalog,
  assetsInAsset,
  vlansInNet,
  subnetsInNet,
  devicesInNet,
  racksInNet,
  deviceRolesInCatalog,
  interfacesInNet,
  transceiversInNet,
  ipAddressesInNet,
  cablesInNet,
  linkGroupsInNet,
  linksInNet,
  linkMediaInNet,
  outletsInNet,
  wanCircuitsInNet,
  ssidsInNet,
  buildingShapesInViz,
  areaShapesInViz,
  locationPlacementsInViz,
  devicePlacementsInViz,
  linkRoutesInViz,
  viewPresetsInViz,
  displaysInViz,
  usersInAuth,
  userPrefsInAuth,
  apiClientsInAuth,
  incidentsInOps,
  changesInOps,
  oncallShiftsInOps,
  notifyChannelsInOps,
  notifyRulesInOps,
  runbooksInOps,
  runsInSync,
  issuesInSync,
  userActionsInAudit,
  deviceVlansInNet,
  tagsInCore,
  entityTagsInCore,
  interfaceVlansInNet,
  userRolesInAuth,
  rolesInAuth,
  changeItemsInOps,
  locationMetricsInCore,
  availabilityMonthlyInOps,
  cableCoresInNet,
  discoveredNeighborsInSync,
} from './schema.js';

export const contactsInCoreRelations = relations(contactsInCore, ({ one }) => ({
  organizationsInCore: one(organizationsInCore, {
    fields: [contactsInCore.orgId],
    references: [organizationsInCore.id],
  }),
}));

export const organizationsInCoreRelations = relations(organizationsInCore, ({ many }) => ({
  contactsInCores: many(contactsInCore),
  assetsInAssets: many(assetsInAsset),
  cablesInNets: many(cablesInNet),
  wanCircuitsInNets: many(wanCircuitsInNet),
  modelsInCatalogs: many(modelsInCatalog),
}));

export const buildingsInCoreRelations = relations(buildingsInCore, ({ one, many }) => ({
  sitesInCore: one(sitesInCore, {
    fields: [buildingsInCore.siteId],
    references: [sitesInCore.id],
  }),
  buildingFormsInCore: one(buildingFormsInCore, {
    fields: [buildingsInCore.formCode],
    references: [buildingFormsInCore.code],
  }),
  buildingShapesInVizs: many(buildingShapesInViz),
  notifyRulesInOps: many(notifyRulesInOps),
  floorsInCores: many(floorsInCore),
  userRolesInAuths: many(userRolesInAuth),
}));

export const sitesInCoreRelations = relations(sitesInCore, ({ many }) => ({
  buildingsInCores: many(buildingsInCore),
  calendarEventsInCores: many(calendarEventsInCore),
  areaShapesInVizs: many(areaShapesInViz),
}));

export const buildingFormsInCoreRelations = relations(buildingFormsInCore, ({ many }) => ({
  buildingsInCores: many(buildingsInCore),
}));

export const locationsInCoreRelations = relations(locationsInCore, ({ one, many }) => ({
  floorsInCore: one(floorsInCore, {
    fields: [locationsInCore.floorId],
    references: [floorsInCore.id],
  }),
  locationTypesInCore: one(locationTypesInCore, {
    fields: [locationsInCore.typeCode],
    references: [locationTypesInCore.code],
  }),
  sourceSystemsInCore: one(sourceSystemsInCore, {
    fields: [locationsInCore.ownerSystem],
    references: [sourceSystemsInCore.code],
  }),
  staffInCore: one(staffInCore, {
    fields: [locationsInCore.verifiedBy],
    references: [staffInCore.id],
  }),
  assetsInAssets: many(assetsInAsset),
  racksInNets: many(racksInNet),
  devicesInNets: many(devicesInNet),
  cablesInNets_aLocationId: many(cablesInNet, {
    relationName: 'cablesInNet_aLocationId_locationsInCore_id',
  }),
  cablesInNets_bLocationId: many(cablesInNet, {
    relationName: 'cablesInNet_bLocationId_locationsInCore_id',
  }),
  outletsInNets: many(outletsInNet),
  locationPlacementsInVizs: many(locationPlacementsInViz),
  displaysInVizs: many(displaysInViz),
  locationMetricsInCores: many(locationMetricsInCore),
}));

export const floorsInCoreRelations = relations(floorsInCore, ({ one, many }) => ({
  locationsInCores: many(locationsInCore),
  devicesInNets: many(devicesInNet),
  buildingsInCore: one(buildingsInCore, {
    fields: [floorsInCore.buildingId],
    references: [buildingsInCore.id],
  }),
}));

export const locationTypesInCoreRelations = relations(locationTypesInCore, ({ many }) => ({
  locationsInCores: many(locationsInCore),
}));

export const sourceSystemsInCoreRelations = relations(sourceSystemsInCore, ({ many }) => ({
  locationsInCores: many(locationsInCore),
  externalRefsInCores: many(externalRefsInCore),
  runsInSyncs: many(runsInSync),
  issuesInSyncs: many(issuesInSync),
  locationMetricsInCores: many(locationMetricsInCore),
}));

export const staffInCoreRelations = relations(staffInCore, ({ many }) => ({
  locationsInCores: many(locationsInCore),
  attachmentsInCores: many(attachmentsInCore),
  devicesInNets: many(devicesInNet),
  viewPresetsInVizs: many(viewPresetsInViz),
  usersInAuths: many(usersInAuth),
  incidentsInOps: many(incidentsInOps),
  changesInOps_requestedBy: many(changesInOps, {
    relationName: 'changesInOps_requestedBy_staffInCore_id',
  }),
  changesInOps_approvedBy: many(changesInOps, {
    relationName: 'changesInOps_approvedBy_staffInCore_id',
  }),
  oncallShiftsInOps: many(oncallShiftsInOps),
}));

export const externalRefsInCoreRelations = relations(externalRefsInCore, ({ one }) => ({
  sourceSystemsInCore: one(sourceSystemsInCore, {
    fields: [externalRefsInCore.systemCode],
    references: [sourceSystemsInCore.code],
  }),
}));

export const attachmentsInCoreRelations = relations(attachmentsInCore, ({ one }) => ({
  staffInCore: one(staffInCore, {
    fields: [attachmentsInCore.uploadedBy],
    references: [staffInCore.id],
  }),
}));

export const calendarEventsInCoreRelations = relations(calendarEventsInCore, ({ one }) => ({
  sitesInCore: one(sitesInCore, {
    fields: [calendarEventsInCore.siteId],
    references: [sitesInCore.id],
  }),
}));

export const assetsInAssetRelations = relations(assetsInAsset, ({ one, many }) => ({
  modelsInCatalog: one(modelsInCatalog, {
    fields: [assetsInAsset.modelId],
    references: [modelsInCatalog.id],
  }),
  locationsInCore: one(locationsInCore, {
    fields: [assetsInAsset.locationId],
    references: [locationsInCore.id],
  }),
  organizationsInCore: one(organizationsInCore, {
    fields: [assetsInAsset.supplierOrgId],
    references: [organizationsInCore.id],
  }),
  devicesInNets: many(devicesInNet),
  ipAddressesInNets: many(ipAddressesInNet),
}));

export const modelsInCatalogRelations = relations(modelsInCatalog, ({ one, many }) => ({
  assetsInAssets: many(assetsInAsset),
  devicesInNets: many(devicesInNet),
  transceiversInNets: many(transceiversInNet),
  runbooksInOps: many(runbooksInOps),
  organizationsInCore: one(organizationsInCore, {
    fields: [modelsInCatalog.vendorOrgId],
    references: [organizationsInCore.id],
  }),
}));

export const subnetsInNetRelations = relations(subnetsInNet, ({ one, many }) => ({
  vlansInNet: one(vlansInNet, {
    fields: [subnetsInNet.vlanId],
    references: [vlansInNet.id],
  }),
  devicesInNet: one(devicesInNet, {
    fields: [subnetsInNet.dhcpServerDeviceId],
    references: [devicesInNet.id],
  }),
  ipAddressesInNets: many(ipAddressesInNet),
}));

export const vlansInNetRelations = relations(vlansInNet, ({ many }) => ({
  subnetsInNets: many(subnetsInNet),
  ssidsInNets: many(ssidsInNet),
  deviceVlansInNets: many(deviceVlansInNet),
  interfaceVlansInNets: many(interfaceVlansInNet),
}));

export const devicesInNetRelations = relations(devicesInNet, ({ one, many }) => ({
  subnetsInNets: many(subnetsInNet),
  deviceRolesInCatalog: one(deviceRolesInCatalog, {
    fields: [devicesInNet.roleCode],
    references: [deviceRolesInCatalog.code],
  }),
  modelsInCatalog: one(modelsInCatalog, {
    fields: [devicesInNet.modelId],
    references: [modelsInCatalog.id],
  }),
  assetsInAsset: one(assetsInAsset, {
    fields: [devicesInNet.assetId],
    references: [assetsInAsset.id],
  }),
  locationsInCore: one(locationsInCore, {
    fields: [devicesInNet.locationId],
    references: [locationsInCore.id],
  }),
  floorsInCore: one(floorsInCore, {
    fields: [devicesInNet.floorId],
    references: [floorsInCore.id],
  }),
  racksInNet: one(racksInNet, {
    fields: [devicesInNet.rackId],
    references: [racksInNet.id],
  }),
  devicesInNet_managedByDeviceId: one(devicesInNet, {
    fields: [devicesInNet.managedByDeviceId],
    references: [devicesInNet.id],
    relationName: 'devicesInNet_managedByDeviceId_devicesInNet_id',
  }),
  devicesInNets_managedByDeviceId: many(devicesInNet, {
    relationName: 'devicesInNet_managedByDeviceId_devicesInNet_id',
  }),
  devicesInNet_powerSourceDeviceId: one(devicesInNet, {
    fields: [devicesInNet.powerSourceDeviceId],
    references: [devicesInNet.id],
    relationName: 'devicesInNet_powerSourceDeviceId_devicesInNet_id',
  }),
  devicesInNets_powerSourceDeviceId: many(devicesInNet, {
    relationName: 'devicesInNet_powerSourceDeviceId_devicesInNet_id',
  }),
  staffInCore: one(staffInCore, {
    fields: [devicesInNet.verifiedBy],
    references: [staffInCore.id],
  }),
  interfacesInNets: many(interfacesInNet),
  ipAddressesInNets: many(ipAddressesInNet),
  linkGroupsInNets_aDeviceId: many(linkGroupsInNet, {
    relationName: 'linkGroupsInNet_aDeviceId_devicesInNet_id',
  }),
  linkGroupsInNets_bDeviceId: many(linkGroupsInNet, {
    relationName: 'linkGroupsInNet_bDeviceId_devicesInNet_id',
  }),
  linksInNets_aDeviceId: many(linksInNet, {
    relationName: 'linksInNet_aDeviceId_devicesInNet_id',
  }),
  linksInNets_bDeviceId: many(linksInNet, {
    relationName: 'linksInNet_bDeviceId_devicesInNet_id',
  }),
  wanCircuitsInNets: many(wanCircuitsInNet),
  ssidsInNets: many(ssidsInNet),
  devicePlacementsInVizs: many(devicePlacementsInViz),
  incidentsInOps_deviceId: many(incidentsInOps, {
    relationName: 'incidentsInOps_deviceId_devicesInNet_id',
  }),
  incidentsInOps_rootDeviceId: many(incidentsInOps, {
    relationName: 'incidentsInOps_rootDeviceId_devicesInNet_id',
  }),
  runbooksInOps: many(runbooksInOps),
  deviceVlansInNets: many(deviceVlansInNet),
  availabilityMonthlyInOps: many(availabilityMonthlyInOps),
  discoveredNeighborsInSyncs: many(discoveredNeighborsInSync),
}));

export const racksInNetRelations = relations(racksInNet, ({ one, many }) => ({
  locationsInCore: one(locationsInCore, {
    fields: [racksInNet.locationId],
    references: [locationsInCore.id],
  }),
  devicesInNets: many(devicesInNet),
}));

export const deviceRolesInCatalogRelations = relations(deviceRolesInCatalog, ({ many }) => ({
  devicesInNets: many(devicesInNet),
  notifyRulesInOps: many(notifyRulesInOps),
  runbooksInOps: many(runbooksInOps),
}));

export const interfacesInNetRelations = relations(interfacesInNet, ({ one, many }) => ({
  devicesInNet: one(devicesInNet, {
    fields: [interfacesInNet.deviceId],
    references: [devicesInNet.id],
  }),
  transceiversInNets: many(transceiversInNet),
  ipAddressesInNets: many(ipAddressesInNet),
  linksInNets_aInterfaceId: many(linksInNet, {
    relationName: 'linksInNet_aInterfaceId_interfacesInNet_id',
  }),
  linksInNets_bInterfaceId: many(linksInNet, {
    relationName: 'linksInNet_bInterfaceId_interfacesInNet_id',
  }),
  outletsInNets_patchInterfaceId: many(outletsInNet, {
    relationName: 'outletsInNet_patchInterfaceId_interfacesInNet_id',
  }),
  outletsInNets_switchInterfaceId: many(outletsInNet, {
    relationName: 'outletsInNet_switchInterfaceId_interfacesInNet_id',
  }),
  wanCircuitsInNets: many(wanCircuitsInNet),
  interfaceVlansInNets: many(interfaceVlansInNet),
  cableCoresInNets_aInterfaceId: many(cableCoresInNet, {
    relationName: 'cableCoresInNet_aInterfaceId_interfacesInNet_id',
  }),
  cableCoresInNets_bInterfaceId: many(cableCoresInNet, {
    relationName: 'cableCoresInNet_bInterfaceId_interfacesInNet_id',
  }),
}));

export const transceiversInNetRelations = relations(transceiversInNet, ({ one }) => ({
  interfacesInNet: one(interfacesInNet, {
    fields: [transceiversInNet.interfaceId],
    references: [interfacesInNet.id],
  }),
  modelsInCatalog: one(modelsInCatalog, {
    fields: [transceiversInNet.modelId],
    references: [modelsInCatalog.id],
  }),
}));

export const ipAddressesInNetRelations = relations(ipAddressesInNet, ({ one }) => ({
  subnetsInNet: one(subnetsInNet, {
    fields: [ipAddressesInNet.subnetId],
    references: [subnetsInNet.id],
  }),
  interfacesInNet: one(interfacesInNet, {
    fields: [ipAddressesInNet.interfaceId],
    references: [interfacesInNet.id],
  }),
  devicesInNet: one(devicesInNet, {
    fields: [ipAddressesInNet.deviceId],
    references: [devicesInNet.id],
  }),
  assetsInAsset: one(assetsInAsset, {
    fields: [ipAddressesInNet.assetId],
    references: [assetsInAsset.id],
  }),
}));

export const cablesInNetRelations = relations(cablesInNet, ({ one, many }) => ({
  locationsInCore_aLocationId: one(locationsInCore, {
    fields: [cablesInNet.aLocationId],
    references: [locationsInCore.id],
    relationName: 'cablesInNet_aLocationId_locationsInCore_id',
  }),
  locationsInCore_bLocationId: one(locationsInCore, {
    fields: [cablesInNet.bLocationId],
    references: [locationsInCore.id],
    relationName: 'cablesInNet_bLocationId_locationsInCore_id',
  }),
  organizationsInCore: one(organizationsInCore, {
    fields: [cablesInNet.installerOrgId],
    references: [organizationsInCore.id],
  }),
  linksInNets: many(linksInNet),
  cableCoresInNets: many(cableCoresInNet),
}));

export const linkGroupsInNetRelations = relations(linkGroupsInNet, ({ one, many }) => ({
  devicesInNet_aDeviceId: one(devicesInNet, {
    fields: [linkGroupsInNet.aDeviceId],
    references: [devicesInNet.id],
    relationName: 'linkGroupsInNet_aDeviceId_devicesInNet_id',
  }),
  devicesInNet_bDeviceId: one(devicesInNet, {
    fields: [linkGroupsInNet.bDeviceId],
    references: [devicesInNet.id],
    relationName: 'linkGroupsInNet_bDeviceId_devicesInNet_id',
  }),
  linksInNets: many(linksInNet),
}));

export const linksInNetRelations = relations(linksInNet, ({ one, many }) => ({
  devicesInNet_aDeviceId: one(devicesInNet, {
    fields: [linksInNet.aDeviceId],
    references: [devicesInNet.id],
    relationName: 'linksInNet_aDeviceId_devicesInNet_id',
  }),
  interfacesInNet_aInterfaceId: one(interfacesInNet, {
    fields: [linksInNet.aInterfaceId],
    references: [interfacesInNet.id],
    relationName: 'linksInNet_aInterfaceId_interfacesInNet_id',
  }),
  devicesInNet_bDeviceId: one(devicesInNet, {
    fields: [linksInNet.bDeviceId],
    references: [devicesInNet.id],
    relationName: 'linksInNet_bDeviceId_devicesInNet_id',
  }),
  interfacesInNet_bInterfaceId: one(interfacesInNet, {
    fields: [linksInNet.bInterfaceId],
    references: [interfacesInNet.id],
    relationName: 'linksInNet_bInterfaceId_interfacesInNet_id',
  }),
  linkMediaInNet: one(linkMediaInNet, {
    fields: [linksInNet.mediaCode],
    references: [linkMediaInNet.code],
  }),
  linkGroupsInNet: one(linkGroupsInNet, {
    fields: [linksInNet.groupId],
    references: [linkGroupsInNet.id],
  }),
  cablesInNet: one(cablesInNet, {
    fields: [linksInNet.cableId],
    references: [cablesInNet.id],
  }),
  linkRoutesInVizs: many(linkRoutesInViz),
  discoveredNeighborsInSyncs: many(discoveredNeighborsInSync),
}));

export const linkMediaInNetRelations = relations(linkMediaInNet, ({ many }) => ({
  linksInNets: many(linksInNet),
}));

export const outletsInNetRelations = relations(outletsInNet, ({ one }) => ({
  locationsInCore: one(locationsInCore, {
    fields: [outletsInNet.locationId],
    references: [locationsInCore.id],
  }),
  interfacesInNet_patchInterfaceId: one(interfacesInNet, {
    fields: [outletsInNet.patchInterfaceId],
    references: [interfacesInNet.id],
    relationName: 'outletsInNet_patchInterfaceId_interfacesInNet_id',
  }),
  interfacesInNet_switchInterfaceId: one(interfacesInNet, {
    fields: [outletsInNet.switchInterfaceId],
    references: [interfacesInNet.id],
    relationName: 'outletsInNet_switchInterfaceId_interfacesInNet_id',
  }),
}));

export const wanCircuitsInNetRelations = relations(wanCircuitsInNet, ({ one }) => ({
  devicesInNet: one(devicesInNet, {
    fields: [wanCircuitsInNet.deviceId],
    references: [devicesInNet.id],
  }),
  organizationsInCore: one(organizationsInCore, {
    fields: [wanCircuitsInNet.providerOrgId],
    references: [organizationsInCore.id],
  }),
  interfacesInNet: one(interfacesInNet, {
    fields: [wanCircuitsInNet.routerInterfaceId],
    references: [interfacesInNet.id],
  }),
}));

export const ssidsInNetRelations = relations(ssidsInNet, ({ one }) => ({
  devicesInNet: one(devicesInNet, {
    fields: [ssidsInNet.controllerDeviceId],
    references: [devicesInNet.id],
  }),
  vlansInNet: one(vlansInNet, {
    fields: [ssidsInNet.vlanId],
    references: [vlansInNet.id],
  }),
}));

export const buildingShapesInVizRelations = relations(buildingShapesInViz, ({ one }) => ({
  buildingsInCore: one(buildingsInCore, {
    fields: [buildingShapesInViz.buildingId],
    references: [buildingsInCore.id],
  }),
}));

export const areaShapesInVizRelations = relations(areaShapesInViz, ({ one }) => ({
  sitesInCore: one(sitesInCore, {
    fields: [areaShapesInViz.siteId],
    references: [sitesInCore.id],
  }),
}));

export const locationPlacementsInVizRelations = relations(locationPlacementsInViz, ({ one }) => ({
  locationsInCore: one(locationsInCore, {
    fields: [locationPlacementsInViz.locationId],
    references: [locationsInCore.id],
  }),
}));

export const devicePlacementsInVizRelations = relations(devicePlacementsInViz, ({ one }) => ({
  devicesInNet: one(devicesInNet, {
    fields: [devicePlacementsInViz.deviceId],
    references: [devicesInNet.id],
  }),
}));

export const linkRoutesInVizRelations = relations(linkRoutesInViz, ({ one }) => ({
  linksInNet: one(linksInNet, {
    fields: [linkRoutesInViz.linkId],
    references: [linksInNet.id],
  }),
}));

export const viewPresetsInVizRelations = relations(viewPresetsInViz, ({ one, many }) => ({
  staffInCore: one(staffInCore, {
    fields: [viewPresetsInViz.createdBy],
    references: [staffInCore.id],
  }),
  displaysInVizs: many(displaysInViz),
}));

export const displaysInVizRelations = relations(displaysInViz, ({ one }) => ({
  locationsInCore: one(locationsInCore, {
    fields: [displaysInViz.locationId],
    references: [locationsInCore.id],
  }),
  viewPresetsInViz: one(viewPresetsInViz, {
    fields: [displaysInViz.presetId],
    references: [viewPresetsInViz.id],
  }),
}));

export const usersInAuthRelations = relations(usersInAuth, ({ one, many }) => ({
  staffInCore: one(staffInCore, {
    fields: [usersInAuth.staffId],
    references: [staffInCore.id],
  }),
  userPrefsInAuths: many(userPrefsInAuth),
  apiClientsInAuths: many(apiClientsInAuth),
  issuesInSyncs: many(issuesInSync),
  userActionsInAudits: many(userActionsInAudit),
  userRolesInAuths: many(userRolesInAuth),
}));

export const userPrefsInAuthRelations = relations(userPrefsInAuth, ({ one }) => ({
  usersInAuth: one(usersInAuth, {
    fields: [userPrefsInAuth.userId],
    references: [usersInAuth.id],
  }),
}));

export const apiClientsInAuthRelations = relations(apiClientsInAuth, ({ one, many }) => ({
  usersInAuth: one(usersInAuth, {
    fields: [apiClientsInAuth.createdBy],
    references: [usersInAuth.id],
  }),
  userActionsInAudits: many(userActionsInAudit),
}));

export const incidentsInOpsRelations = relations(incidentsInOps, ({ one }) => ({
  devicesInNet_deviceId: one(devicesInNet, {
    fields: [incidentsInOps.deviceId],
    references: [devicesInNet.id],
    relationName: 'incidentsInOps_deviceId_devicesInNet_id',
  }),
  devicesInNet_rootDeviceId: one(devicesInNet, {
    fields: [incidentsInOps.rootDeviceId],
    references: [devicesInNet.id],
    relationName: 'incidentsInOps_rootDeviceId_devicesInNet_id',
  }),
  staffInCore: one(staffInCore, {
    fields: [incidentsInOps.ackedBy],
    references: [staffInCore.id],
  }),
}));

export const changesInOpsRelations = relations(changesInOps, ({ one, many }) => ({
  staffInCore_requestedBy: one(staffInCore, {
    fields: [changesInOps.requestedBy],
    references: [staffInCore.id],
    relationName: 'changesInOps_requestedBy_staffInCore_id',
  }),
  staffInCore_approvedBy: one(staffInCore, {
    fields: [changesInOps.approvedBy],
    references: [staffInCore.id],
    relationName: 'changesInOps_approvedBy_staffInCore_id',
  }),
  changeItemsInOps: many(changeItemsInOps),
}));

export const oncallShiftsInOpsRelations = relations(oncallShiftsInOps, ({ one }) => ({
  staffInCore: one(staffInCore, {
    fields: [oncallShiftsInOps.staffId],
    references: [staffInCore.id],
  }),
}));

export const notifyRulesInOpsRelations = relations(notifyRulesInOps, ({ one }) => ({
  notifyChannelsInOp: one(notifyChannelsInOps, {
    fields: [notifyRulesInOps.channelId],
    references: [notifyChannelsInOps.id],
  }),
  buildingsInCore: one(buildingsInCore, {
    fields: [notifyRulesInOps.buildingId],
    references: [buildingsInCore.id],
  }),
  deviceRolesInCatalog: one(deviceRolesInCatalog, {
    fields: [notifyRulesInOps.roleCode],
    references: [deviceRolesInCatalog.code],
  }),
}));

export const notifyChannelsInOpsRelations = relations(notifyChannelsInOps, ({ many }) => ({
  notifyRulesInOps: many(notifyRulesInOps),
}));

export const runbooksInOpsRelations = relations(runbooksInOps, ({ one }) => ({
  deviceRolesInCatalog: one(deviceRolesInCatalog, {
    fields: [runbooksInOps.roleCode],
    references: [deviceRolesInCatalog.code],
  }),
  modelsInCatalog: one(modelsInCatalog, {
    fields: [runbooksInOps.modelId],
    references: [modelsInCatalog.id],
  }),
  devicesInNet: one(devicesInNet, {
    fields: [runbooksInOps.deviceId],
    references: [devicesInNet.id],
  }),
}));

export const runsInSyncRelations = relations(runsInSync, ({ one, many }) => ({
  sourceSystemsInCore: one(sourceSystemsInCore, {
    fields: [runsInSync.systemCode],
    references: [sourceSystemsInCore.code],
  }),
  issuesInSyncs: many(issuesInSync),
}));

export const issuesInSyncRelations = relations(issuesInSync, ({ one }) => ({
  runsInSync: one(runsInSync, {
    fields: [issuesInSync.runId],
    references: [runsInSync.id],
  }),
  sourceSystemsInCore: one(sourceSystemsInCore, {
    fields: [issuesInSync.systemCode],
    references: [sourceSystemsInCore.code],
  }),
  usersInAuth: one(usersInAuth, {
    fields: [issuesInSync.resolvedBy],
    references: [usersInAuth.id],
  }),
}));

export const userActionsInAuditRelations = relations(userActionsInAudit, ({ one }) => ({
  usersInAuth: one(usersInAuth, {
    fields: [userActionsInAudit.userId],
    references: [usersInAuth.id],
  }),
  apiClientsInAuth: one(apiClientsInAuth, {
    fields: [userActionsInAudit.apiClientId],
    references: [apiClientsInAuth.id],
  }),
}));

export const deviceVlansInNetRelations = relations(deviceVlansInNet, ({ one }) => ({
  devicesInNet: one(devicesInNet, {
    fields: [deviceVlansInNet.deviceId],
    references: [devicesInNet.id],
  }),
  vlansInNet: one(vlansInNet, {
    fields: [deviceVlansInNet.vlanId],
    references: [vlansInNet.id],
  }),
}));

export const entityTagsInCoreRelations = relations(entityTagsInCore, ({ one }) => ({
  tagsInCore: one(tagsInCore, {
    fields: [entityTagsInCore.tagId],
    references: [tagsInCore.id],
  }),
}));

export const tagsInCoreRelations = relations(tagsInCore, ({ many }) => ({
  entityTagsInCores: many(entityTagsInCore),
}));

export const interfaceVlansInNetRelations = relations(interfaceVlansInNet, ({ one }) => ({
  interfacesInNet: one(interfacesInNet, {
    fields: [interfaceVlansInNet.interfaceId],
    references: [interfacesInNet.id],
  }),
  vlansInNet: one(vlansInNet, {
    fields: [interfaceVlansInNet.vlanId],
    references: [vlansInNet.id],
  }),
}));

export const userRolesInAuthRelations = relations(userRolesInAuth, ({ one }) => ({
  usersInAuth: one(usersInAuth, {
    fields: [userRolesInAuth.userId],
    references: [usersInAuth.id],
  }),
  rolesInAuth: one(rolesInAuth, {
    fields: [userRolesInAuth.roleCode],
    references: [rolesInAuth.code],
  }),
  buildingsInCore: one(buildingsInCore, {
    fields: [userRolesInAuth.scopeBuildingId],
    references: [buildingsInCore.id],
  }),
}));

export const rolesInAuthRelations = relations(rolesInAuth, ({ many }) => ({
  userRolesInAuths: many(userRolesInAuth),
}));

export const changeItemsInOpsRelations = relations(changeItemsInOps, ({ one }) => ({
  changesInOp: one(changesInOps, {
    fields: [changeItemsInOps.changeId],
    references: [changesInOps.id],
  }),
}));

export const locationMetricsInCoreRelations = relations(locationMetricsInCore, ({ one }) => ({
  locationsInCore: one(locationsInCore, {
    fields: [locationMetricsInCore.locationId],
    references: [locationsInCore.id],
  }),
  sourceSystemsInCore: one(sourceSystemsInCore, {
    fields: [locationMetricsInCore.source],
    references: [sourceSystemsInCore.code],
  }),
}));

export const availabilityMonthlyInOpsRelations = relations(availabilityMonthlyInOps, ({ one }) => ({
  devicesInNet: one(devicesInNet, {
    fields: [availabilityMonthlyInOps.deviceId],
    references: [devicesInNet.id],
  }),
}));

export const cableCoresInNetRelations = relations(cableCoresInNet, ({ one }) => ({
  cablesInNet: one(cablesInNet, {
    fields: [cableCoresInNet.cableId],
    references: [cablesInNet.id],
  }),
  interfacesInNet_aInterfaceId: one(interfacesInNet, {
    fields: [cableCoresInNet.aInterfaceId],
    references: [interfacesInNet.id],
    relationName: 'cableCoresInNet_aInterfaceId_interfacesInNet_id',
  }),
  interfacesInNet_bInterfaceId: one(interfacesInNet, {
    fields: [cableCoresInNet.bInterfaceId],
    references: [interfacesInNet.id],
    relationName: 'cableCoresInNet_bInterfaceId_interfacesInNet_id',
  }),
}));

export const discoveredNeighborsInSyncRelations = relations(
  discoveredNeighborsInSync,
  ({ one }) => ({
    devicesInNet: one(devicesInNet, {
      fields: [discoveredNeighborsInSync.deviceId],
      references: [devicesInNet.id],
    }),
    linksInNet: one(linksInNet, {
      fields: [discoveredNeighborsInSync.matchedLinkId],
      references: [linksInNet.id],
    }),
  }),
);
