// GENERATED by `pnpm db:pull` (drizzle-kit pull) from a database migrated with migrations/*.sql.
// Do not edit by hand — change the SQL migration, migrate a scratch DB, then re-run db:pull (ADR-0018).
import {
  pgTable,
  pgSchema,
  unique,
  uuid,
  text,
  jsonb,
  timestamp,
  integer,
  foreignKey,
  boolean,
  check,
  smallint,
  index,
  serial,
  time,
  date,
  cidr,
  inet,
  uniqueIndex,
  macaddr,
  numeric,
  bigserial,
  bigint,
  primaryKey,
} from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';

export const core = pgSchema('core');
export const catalog = pgSchema('catalog');
export const asset = pgSchema('asset');
export const net = pgSchema('net');
export const viz = pgSchema('viz');
export const auth = pgSchema('auth');
export const ops = pgSchema('ops');
export const sync = pgSchema('sync');
export const audit = pgSchema('audit');
export const api = pgSchema('api');

export const locCodeSeqInCore = core.sequence('loc_code_seq', {
  startWith: '188',
  increment: '1',
  minValue: '1',
  maxValue: '9223372036854775807',
  cache: '1',
  cycle: false,
});

export const organizationsInCore = core.table(
  'organizations',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    name: text().notNull(),
    kinds: text()
      .array()
      .default(sql`'{}'`)
      .notNull(),
    website: text(),
    notes: text(),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [unique('organizations_code_key').on(table.code)],
);

export const contactsInCore = core.table(
  'contacts',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    orgId: uuid('org_id').notNull(),
    name: text().notNull(),
    role: text(),
    phone: text(),
    email: text(),
    lineId: text('line_id'),
    notes: text(),
    active: boolean().default(true).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.orgId],
      foreignColumns: [organizationsInCore.id],
      name: 'contacts_org_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const sitesInCore = core.table(
  'sites',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    name: text().notNull(),
    timezone: text().default('Asia/Bangkok').notNull(),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [unique('sites_code_key').on(table.code)],
);

export const buildingsInCore = core.table(
  'buildings',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    siteId: uuid('site_id').notNull(),
    code: text().notNull(),
    name: text().notNull(),
    nameEn: text('name_en'),
    aliases: text()
      .array()
      .default(sql`'{}'`)
      .notNull(),
    assetName: text('asset_name'),
    formCode: text('form_code'),
    floorCount: smallint('floor_count').notNull(),
    roomsPerFloor: smallint('rooms_per_floor'),
    hasNetwork: boolean('has_network').default(true).notNull(),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.siteId],
      foreignColumns: [sitesInCore.id],
      name: 'buildings_site_id_fkey',
    }),
    foreignKey({
      columns: [table.formCode],
      foreignColumns: [buildingFormsInCore.code],
      name: 'buildings_form_code_fkey',
    }),
    unique('buildings_site_id_code_key').on(table.siteId, table.code),
    check('buildings_floor_count_check', sql`floor_count >= 0`),
  ],
);

export const buildingFormsInCore = core.table('building_forms', {
  code: text().primaryKey().notNull(),
  name: text().notNull(),
});

export const locationsInCore = core.table(
  'locations',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    locCode: text('loc_code').notNull(),
    floorId: uuid('floor_id').notNull(),
    name: text().notNull(),
    nameEn: text('name_en'),
    roomNumber: text('room_number'),
    typeCode: text('type_code'),
    corridorOrder: smallint('corridor_order'),
    side: text(),
    hasRack: boolean('has_rack').default(false).notNull(),
    ownerSystem: text('owner_system').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }),
    verifiedBy: uuid('verified_by'),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    index('locations_name_trgm').using('gin', table.name.asc().nullsLast().op('gin_trgm_ops')),
    foreignKey({
      columns: [table.floorId],
      foreignColumns: [floorsInCore.id],
      name: 'locations_floor_id_fkey',
    }),
    foreignKey({
      columns: [table.typeCode],
      foreignColumns: [locationTypesInCore.code],
      name: 'locations_type_code_fkey',
    }),
    foreignKey({
      columns: [table.ownerSystem],
      foreignColumns: [sourceSystemsInCore.code],
      name: 'locations_owner_system_fkey',
    }),
    foreignKey({
      columns: [table.verifiedBy],
      foreignColumns: [staffInCore.id],
      name: 'locations_verified_by_fkey',
    }),
    unique('locations_loc_code_key').on(table.locCode),
  ],
);

export const locationTypesInCore = core.table('location_types', {
  code: text().primaryKey().notNull(),
  name: text().notNull(),
});

export const sourceSystemsInCore = core.table('source_systems', {
  code: text().primaryKey().notNull(),
  name: text().notNull(),
  baseUrl: text('base_url'),
  notes: text(),
});

export const staffInCore = core.table(
  'staff',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    staffCode: text('staff_code').notNull(),
    fullName: text('full_name').notNull(),
    email: text(),
    phone: text(),
    active: boolean().default(true).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
  },
  (table) => [
    unique('staff_staff_code_key').on(table.staffCode),
    unique('staff_email_key').on(table.email),
  ],
);

export const externalRefsInCore = core.table(
  'external_refs',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    entityTable: text('entity_table').notNull(),
    entityId: uuid('entity_id').notNull(),
    systemCode: text('system_code').notNull(),
    externalId: text('external_id').notNull(),
    externalKey: text('external_key'),
    url: text(),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.systemCode],
      foreignColumns: [sourceSystemsInCore.code],
      name: 'external_refs_system_code_fkey',
    }),
    unique('external_refs_system_code_entity_table_external_id_key').on(
      table.entityTable,
      table.systemCode,
      table.externalId,
    ),
    unique('external_refs_entity_table_entity_id_system_code_key').on(
      table.entityTable,
      table.entityId,
      table.systemCode,
    ),
  ],
);

export const tagsInCore = core.table(
  'tags',
  {
    id: serial().primaryKey().notNull(),
    name: text().notNull(),
  },
  (table) => [unique('tags_name_key').on(table.name)],
);

export const attachmentsInCore = core.table(
  'attachments',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    entityTable: text('entity_table').notNull(),
    entityId: uuid('entity_id').notNull(),
    kind: text().notNull(),
    title: text().notNull(),
    url: text().notNull(),
    driveFileId: text('drive_file_id'),
    mimeType: text('mime_type'),
    uploadedBy: uuid('uploaded_by'),
    uploadedAt: timestamp('uploaded_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    index('attachments_entity').using(
      'btree',
      table.entityTable.asc().nullsLast().op('text_ops'),
      table.entityId.asc().nullsLast().op('text_ops'),
    ),
    foreignKey({
      columns: [table.uploadedBy],
      foreignColumns: [staffInCore.id],
      name: 'attachments_uploaded_by_fkey',
    }),
  ],
);

export const calendarEventsInCore = core.table(
  'calendar_events',
  {
    id: serial().primaryKey().notNull(),
    siteId: uuid('site_id').notNull(),
    kind: text().notNull(),
    name: text().notNull(),
    startsAt: timestamp('starts_at', { withTimezone: true, mode: 'string' }),
    endsAt: timestamp('ends_at', { withTimezone: true, mode: 'string' }),
    rrule: text(),
    timeStart: time('time_start'),
    timeEnd: time('time_end'),
  },
  (table) => [
    foreignKey({
      columns: [table.siteId],
      foreignColumns: [sitesInCore.id],
      name: 'calendar_events_site_id_fkey',
    }),
  ],
);

export const assetsInAsset = asset.table(
  'assets',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    assetTag: text('asset_tag'),
    sbaCode: text('sba_code'),
    category: text().notNull(),
    modelId: integer('model_id'),
    serialNo: text('serial_no'),
    locationId: uuid('location_id'),
    status: text().default('in_use').notNull(),
    purchaseDate: date('purchase_date'),
    poNumber: text('po_number'),
    supplierOrgId: uuid('supplier_org_id'),
    warrantyUntil: date('warranty_until'),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.modelId],
      foreignColumns: [modelsInCatalog.id],
      name: 'assets_model_id_fkey',
    }),
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'assets_location_id_fkey',
    }),
    foreignKey({
      columns: [table.supplierOrgId],
      foreignColumns: [organizationsInCore.id],
      name: 'assets_supplier_org_id_fkey',
    }),
    unique('assets_asset_tag_key').on(table.assetTag),
    unique('assets_sba_code_key').on(table.sbaCode),
  ],
);

export const deviceRolesInCatalog = catalog.table('device_roles', {
  code: text().primaryKey().notNull(),
  name: text().notNull(),
  layer: text().notNull(),
  monitored: boolean().default(true).notNull(),
});

export const vlansInNet = net.table(
  'vlans',
  {
    id: serial().primaryKey().notNull(),
    vid: smallint().notNull(),
    name: text().notNull(),
    purpose: text(),
    planned: boolean().default(false).notNull(),
  },
  (table) => [
    unique('vlans_vid_key').on(table.vid),
    check('vlans_vid_check', sql`(vid >= 1) AND (vid <= 4094)`),
  ],
);

export const subnetsInNet = net.table(
  'subnets',
  {
    id: serial().primaryKey().notNull(),
    cidr: cidr().notNull(),
    vlanId: integer('vlan_id'),
    gateway: inet(),
    dhcpServerDeviceId: uuid('dhcp_server_device_id'),
    dhcpStart: inet('dhcp_start'),
    dhcpEnd: inet('dhcp_end'),
    notes: text(),
  },
  (table) => [
    foreignKey({
      columns: [table.vlanId],
      foreignColumns: [vlansInNet.id],
      name: 'subnets_vlan_id_fkey',
    }),
    foreignKey({
      columns: [table.dhcpServerDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'subnets_dhcp_fk',
    }),
    unique('subnets_cidr_key').on(table.cidr),
  ],
);

export const racksInNet = net.table(
  'racks',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    locationId: uuid('location_id').notNull(),
    uHeight: smallint('u_height').default(42).notNull(),
    kind: text().default('rack').notNull(),
    notes: text(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'racks_location_id_fkey',
    }),
    unique('racks_code_key').on(table.code),
  ],
);

export const devicesInNet = net.table(
  'devices',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    displayName: text('display_name').notNull(),
    hostname: text(),
    roleCode: text('role_code').notNull(),
    modelId: integer('model_id'),
    assetId: uuid('asset_id'),
    locationId: uuid('location_id'),
    floorId: uuid('floor_id'),
    rackId: uuid('rack_id'),
    rackUStart: smallint('rack_u_start'),
    rackUSize: smallint('rack_u_size'),
    managedByDeviceId: uuid('managed_by_device_id'),
    powerSourceDeviceId: uuid('power_source_device_id'),
    poePowered: boolean('poe_powered').default(false).notNull(),
    mgmtIp: inet('mgmt_ip'),
    mac: macaddr(),
    firmwareVersion: text('firmware_version'),
    mgmtProtocols: text('mgmt_protocols')
      .array()
      .default(sql`'{}'`)
      .notNull(),
    secretRef: text('secret_ref'),
    lifecycle: text().default('active').notNull(),
    dataStatus: text('data_status').default('unverified').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }),
    verifiedBy: uuid('verified_by'),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    index('devices_managed_by').using(
      'btree',
      table.managedByDeviceId.asc().nullsLast().op('uuid_ops'),
    ),
    uniqueIndex('devices_mgmt_ip_uq')
      .using('btree', table.mgmtIp.asc().nullsLast().op('inet_ops'))
      .where(sql`((mgmt_ip IS NOT NULL) AND (deleted_at IS NULL))`),
    index('devices_name_trgm').using('gin', table.displayName.asc().nullsLast().op('gin_trgm_ops')),
    foreignKey({
      columns: [table.roleCode],
      foreignColumns: [deviceRolesInCatalog.code],
      name: 'devices_role_code_fkey',
    }),
    foreignKey({
      columns: [table.modelId],
      foreignColumns: [modelsInCatalog.id],
      name: 'devices_model_id_fkey',
    }),
    foreignKey({
      columns: [table.assetId],
      foreignColumns: [assetsInAsset.id],
      name: 'devices_asset_id_fkey',
    }),
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'devices_location_id_fkey',
    }),
    foreignKey({
      columns: [table.floorId],
      foreignColumns: [floorsInCore.id],
      name: 'devices_floor_id_fkey',
    }),
    foreignKey({
      columns: [table.rackId],
      foreignColumns: [racksInNet.id],
      name: 'devices_rack_id_fkey',
    }),
    foreignKey({
      columns: [table.managedByDeviceId],
      foreignColumns: [table.id],
      name: 'devices_managed_by_device_id_fkey',
    }),
    foreignKey({
      columns: [table.powerSourceDeviceId],
      foreignColumns: [table.id],
      name: 'devices_power_source_device_id_fkey',
    }),
    foreignKey({
      columns: [table.verifiedBy],
      foreignColumns: [staffInCore.id],
      name: 'devices_verified_by_fkey',
    }),
    unique('devices_code_key').on(table.code),
    unique('devices_asset_id_key').on(table.assetId),
    check(
      'devices_check',
      sql`(location_id IS NOT NULL) OR (floor_id IS NOT NULL) OR (role_code = ANY (ARRAY['wan'::text, 'controller'::text]))`,
    ),
    check('devices_check1', sql`(managed_by_device_id IS NULL) OR (managed_by_device_id <> id)`),
  ],
);

export const interfacesInNet = net.table(
  'interfaces',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    deviceId: uuid('device_id').notNull(),
    name: text().notNull(),
    kind: text().notNull(),
    speedMbps: integer('speed_mbps'),
    poe: boolean().default(false).notNull(),
    mac: macaddr(),
    description: text(),
    zabbixItemkey: text('zabbix_itemkey'),
  },
  (table) => [
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'interfaces_device_id_fkey',
    }).onDelete('cascade'),
    unique('interfaces_device_id_name_key').on(table.deviceId, table.name),
  ],
);

export const transceiversInNet = net.table(
  'transceivers',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    interfaceId: uuid('interface_id'),
    modelId: integer('model_id'),
    formFactor: text('form_factor'),
    standard: text(),
    wavelengthNm: smallint('wavelength_nm'),
    fiberMode: text('fiber_mode'),
    serialNo: text('serial_no'),
    status: text().default('installed').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.interfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'transceivers_interface_id_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.modelId],
      foreignColumns: [modelsInCatalog.id],
      name: 'transceivers_model_id_fkey',
    }),
    unique('transceivers_interface_id_key').on(table.interfaceId),
  ],
);

export const ipAddressesInNet = net.table(
  'ip_addresses',
  {
    id: serial().primaryKey().notNull(),
    address: inet().notNull(),
    subnetId: integer('subnet_id'),
    interfaceId: uuid('interface_id'),
    deviceId: uuid('device_id'),
    assetId: uuid('asset_id'),
    role: text().default('primary').notNull(),
    reserved: boolean().default(false).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.subnetId],
      foreignColumns: [subnetsInNet.id],
      name: 'ip_addresses_subnet_id_fkey',
    }),
    foreignKey({
      columns: [table.interfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'ip_addresses_interface_id_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'ip_addresses_device_id_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.assetId],
      foreignColumns: [assetsInAsset.id],
      name: 'ip_addresses_asset_id_fkey',
    }).onDelete('set null'),
    unique('ip_addresses_address_key').on(table.address),
  ],
);

export const cablesInNet = net.table(
  'cables',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    kind: text().notNull(),
    coreCount: smallint('core_count'),
    lengthM: integer('length_m'),
    aLocationId: uuid('a_location_id'),
    bLocationId: uuid('b_location_id'),
    routeNote: text('route_note'),
    installedAt: date('installed_at'),
    installerOrgId: uuid('installer_org_id'),
    status: text().default('in_use').notNull(),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.aLocationId],
      foreignColumns: [locationsInCore.id],
      name: 'cables_a_location_id_fkey',
    }),
    foreignKey({
      columns: [table.bLocationId],
      foreignColumns: [locationsInCore.id],
      name: 'cables_b_location_id_fkey',
    }),
    foreignKey({
      columns: [table.installerOrgId],
      foreignColumns: [organizationsInCore.id],
      name: 'cables_installer_org_id_fkey',
    }),
    unique('cables_code_key').on(table.code),
  ],
);

export const linkGroupsInNet = net.table(
  'link_groups',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    kind: text().default('lacp').notNull(),
    aDeviceId: uuid('a_device_id').notNull(),
    bDeviceId: uuid('b_device_id').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.aDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'link_groups_a_device_id_fkey',
    }),
    foreignKey({
      columns: [table.bDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'link_groups_b_device_id_fkey',
    }),
    unique('link_groups_code_key').on(table.code),
  ],
);

export const linksInNet = net.table(
  'links',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text(),
    aDeviceId: uuid('a_device_id').notNull(),
    aInterfaceId: uuid('a_interface_id'),
    bDeviceId: uuid('b_device_id').notNull(),
    bInterfaceId: uuid('b_interface_id'),
    mediaCode: text('media_code').notNull(),
    isUplink: boolean('is_uplink').default(true).notNull(),
    groupId: uuid('group_id'),
    cableId: uuid('cable_id'),
    cableCores: smallint('cable_cores').array(),
    speedMbps: integer('speed_mbps'),
    attributes: jsonb().default({}).notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    uniqueIndex('links_one_uplink')
      .using('btree', table.bDeviceId.asc().nullsLast().op('uuid_ops'))
      .where(sql`(is_uplink AND (deleted_at IS NULL))`),
    foreignKey({
      columns: [table.aDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'links_a_device_id_fkey',
    }),
    foreignKey({
      columns: [table.aInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'links_a_interface_id_fkey',
    }),
    foreignKey({
      columns: [table.bDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'links_b_device_id_fkey',
    }),
    foreignKey({
      columns: [table.bInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'links_b_interface_id_fkey',
    }),
    foreignKey({
      columns: [table.mediaCode],
      foreignColumns: [linkMediaInNet.code],
      name: 'links_media_code_fkey',
    }),
    foreignKey({
      columns: [table.groupId],
      foreignColumns: [linkGroupsInNet.id],
      name: 'links_group_id_fkey',
    }),
    foreignKey({
      columns: [table.cableId],
      foreignColumns: [cablesInNet.id],
      name: 'links_cable_id_fkey',
    }),
    unique('links_code_key').on(table.code),
    check('links_check', sql`a_device_id <> b_device_id`),
  ],
);

export const linkMediaInNet = net.table('link_media', {
  code: text().primaryKey().notNull(),
  name: text().notNull(),
});

export const outletsInNet = net.table(
  'outlets',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    locationId: uuid('location_id').notNull(),
    purpose: text(),
    patchInterfaceId: uuid('patch_interface_id'),
    switchInterfaceId: uuid('switch_interface_id'),
    status: text().default('active').notNull(),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'outlets_location_id_fkey',
    }),
    foreignKey({
      columns: [table.patchInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'outlets_patch_interface_id_fkey',
    }),
    foreignKey({
      columns: [table.switchInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'outlets_switch_interface_id_fkey',
    }),
    unique('outlets_code_key').on(table.code),
  ],
);

export const wanCircuitsInNet = net.table(
  'wan_circuits',
  {
    id: serial().primaryKey().notNull(),
    deviceId: uuid('device_id').notNull(),
    providerOrgId: uuid('provider_org_id').notNull(),
    circuitRef: text('circuit_ref'),
    priority: smallint().notNull(),
    bandwidthDownMbps: integer('bandwidth_down_mbps'),
    bandwidthUpMbps: integer('bandwidth_up_mbps'),
    publicIps: inet('public_ips').array(),
    contractNo: text('contract_no'),
    contractStart: date('contract_start'),
    contractEnd: date('contract_end'),
    monthlyCost: numeric('monthly_cost', { precision: 12, scale: 2 }),
    slaText: text('sla_text'),
    routerInterfaceId: uuid('router_interface_id'),
    notes: text(),
  },
  (table) => [
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'wan_circuits_device_id_fkey',
    }),
    foreignKey({
      columns: [table.providerOrgId],
      foreignColumns: [organizationsInCore.id],
      name: 'wan_circuits_provider_org_id_fkey',
    }),
    foreignKey({
      columns: [table.routerInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'wan_circuits_router_interface_id_fkey',
    }),
    unique('wan_circuits_device_id_key').on(table.deviceId),
  ],
);

export const ssidsInNet = net.table(
  'ssids',
  {
    id: serial().primaryKey().notNull(),
    name: text().notNull(),
    controllerDeviceId: uuid('controller_device_id'),
    vlanId: integer('vlan_id'),
    bands: text()
      .array()
      .default(sql`'{}'`)
      .notNull(),
    security: text(),
    audience: text(),
    active: boolean().default(true).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.controllerDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'ssids_controller_device_id_fkey',
    }),
    foreignKey({
      columns: [table.vlanId],
      foreignColumns: [vlansInNet.id],
      name: 'ssids_vlan_id_fkey',
    }),
    unique('ssids_controller_device_id_name_key').on(table.name, table.controllerDeviceId),
  ],
);

export const buildingShapesInViz = viz.table(
  'building_shapes',
  {
    buildingId: uuid('building_id').primaryKey().notNull(),
    x: numeric().notNull(),
    z: numeric().notNull(),
    width: numeric().notNull(),
    depth: numeric().notNull(),
    rotation: numeric().default('0').notNull(),
    floorHeight: numeric('floor_height').default('0.9').notNull(),
    shape: jsonb().default({}).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.buildingId],
      foreignColumns: [buildingsInCore.id],
      name: 'building_shapes_building_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const areaShapesInViz = viz.table(
  'area_shapes',
  {
    id: serial().primaryKey().notNull(),
    siteId: uuid('site_id').notNull(),
    code: text().notNull(),
    name: text().notNull(),
    kind: text().notNull(),
    x: numeric().notNull(),
    z: numeric().notNull(),
    width: numeric().notNull(),
    depth: numeric().notNull(),
    rotation: numeric().default('0').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.siteId],
      foreignColumns: [sitesInCore.id],
      name: 'area_shapes_site_id_fkey',
    }),
    unique('area_shapes_site_id_code_key').on(table.siteId, table.code),
  ],
);

export const locationPlacementsInViz = viz.table(
  'location_placements',
  {
    locationId: uuid('location_id').primaryKey().notNull(),
    mode: text().default('auto').notNull(),
    u: numeric(),
    v: numeric(),
    spanU: numeric('span_u'),
    spanV: numeric('span_v'),
  },
  (table) => [
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'location_placements_location_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const devicePlacementsInViz = viz.table(
  'device_placements',
  {
    deviceId: uuid('device_id').primaryKey().notNull(),
    mode: text().default('auto').notNull(),
    u: numeric(),
    v: numeric(),
    heightOffset: numeric('height_offset').default('0').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'device_placements_device_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const linkRoutesInViz = viz.table(
  'link_routes',
  {
    linkId: uuid('link_id').primaryKey().notNull(),
    color: text(),
    lane: smallint(),
    waypoints: jsonb().default([]).notNull(),
    rule: text(),
  },
  (table) => [
    foreignKey({
      columns: [table.linkId],
      foreignColumns: [linksInNet.id],
      name: 'link_routes_link_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const viewPresetsInViz = viz.table(
  'view_presets',
  {
    id: serial().primaryKey().notNull(),
    name: text().notNull(),
    camera: jsonb().notNull(),
    createdBy: uuid('created_by'),
  },
  (table) => [
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [staffInCore.id],
      name: 'view_presets_created_by_fkey',
    }),
    unique('view_presets_name_key').on(table.name),
  ],
);

export const displaysInViz = viz.table(
  'displays',
  {
    id: serial().primaryKey().notNull(),
    code: text().notNull(),
    name: text().notNull(),
    locationId: uuid('location_id'),
    presetId: integer('preset_id'),
    cycleSeconds: smallint('cycle_seconds').default(10).notNull(),
    sound: boolean().default(true).notNull(),
    ecoMode: text('eco_mode').default('auto').notNull(),
    layers: jsonb().default({}).notNull(),
    displayTokenHash: text('display_token_hash'),
    lastSeenAt: timestamp('last_seen_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'displays_location_id_fkey',
    }),
    foreignKey({
      columns: [table.presetId],
      foreignColumns: [viewPresetsInViz.id],
      name: 'displays_preset_id_fkey',
    }),
    unique('displays_code_key').on(table.code),
  ],
);

export const usersInAuth = auth.table(
  'users',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    email: text().notNull(),
    staffId: uuid('staff_id'),
    active: boolean().default(true).notNull(),
    lastLoginAt: timestamp('last_login_at', { withTimezone: true, mode: 'string' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.staffId],
      foreignColumns: [staffInCore.id],
      name: 'users_staff_id_fkey',
    }),
    unique('users_email_key').on(table.email),
  ],
);

export const rolesInAuth = auth.table('roles', {
  code: text().primaryKey().notNull(),
  name: text().notNull(),
});

export const userPrefsInAuth = auth.table(
  'user_prefs',
  {
    userId: uuid('user_id').primaryKey().notNull(),
    prefs: jsonb().default({}).notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.userId],
      foreignColumns: [usersInAuth.id],
      name: 'user_prefs_user_id_fkey',
    }).onDelete('cascade'),
  ],
);

export const apiClientsInAuth = auth.table(
  'api_clients',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    name: text().notNull(),
    tokenHash: text('token_hash').notNull(),
    scopes: text()
      .array()
      .default(sql`'{}'`)
      .notNull(),
    createdBy: uuid('created_by'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    lastUsedAt: timestamp('last_used_at', { withTimezone: true, mode: 'string' }),
    expiresAt: timestamp('expires_at', { withTimezone: true, mode: 'string' }),
    revokedAt: timestamp('revoked_at', { withTimezone: true, mode: 'string' }),
  },
  (table) => [
    foreignKey({
      columns: [table.createdBy],
      foreignColumns: [usersInAuth.id],
      name: 'api_clients_created_by_fkey',
    }),
    unique('api_clients_name_key').on(table.name),
  ],
);

export const incidentsInOps = ops.table(
  'incidents',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    zabbixEventid: text('zabbix_eventid'),
    deviceId: uuid('device_id'),
    rootDeviceId: uuid('root_device_id'),
    severity: text().notNull(),
    summary: text().notNull(),
    startedAt: timestamp('started_at', { withTimezone: true, mode: 'string' }).notNull(),
    endedAt: timestamp('ended_at', { withTimezone: true, mode: 'string' }),
    affectedCount: integer('affected_count').default(0).notNull(),
    ackedAt: timestamp('acked_at', { withTimezone: true, mode: 'string' }),
    ackedBy: uuid('acked_by'),
    ackNote: text('ack_note'),
    causeCode: text('cause_code'),
    resolution: text(),
    glpiTicketId: text('glpi_ticket_id'),
    inSchoolHours: boolean('in_school_hours'),
  },
  (table) => [
    index('incidents_time').using(
      'btree',
      table.startedAt.desc().nullsFirst().op('timestamptz_ops'),
    ),
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'incidents_device_id_fkey',
    }),
    foreignKey({
      columns: [table.rootDeviceId],
      foreignColumns: [devicesInNet.id],
      name: 'incidents_root_device_id_fkey',
    }),
    foreignKey({
      columns: [table.ackedBy],
      foreignColumns: [staffInCore.id],
      name: 'incidents_acked_by_fkey',
    }),
    unique('incidents_zabbix_eventid_key').on(table.zabbixEventid),
  ],
);

export const changesInOps = ops.table(
  'changes',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    code: text().notNull(),
    title: text().notNull(),
    description: text(),
    risk: text().default('low').notNull(),
    status: text().default('draft').notNull(),
    plannedStart: timestamp('planned_start', { withTimezone: true, mode: 'string' }),
    plannedEnd: timestamp('planned_end', { withTimezone: true, mode: 'string' }),
    actualStart: timestamp('actual_start', { withTimezone: true, mode: 'string' }),
    actualEnd: timestamp('actual_end', { withTimezone: true, mode: 'string' }),
    requestedBy: uuid('requested_by'),
    approvedBy: uuid('approved_by'),
    zabbixMaintenanceid: text('zabbix_maintenanceid'),
    glpiTicketId: text('glpi_ticket_id'),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    rowVersion: integer('row_version').default(1).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.requestedBy],
      foreignColumns: [staffInCore.id],
      name: 'changes_requested_by_fkey',
    }),
    foreignKey({
      columns: [table.approvedBy],
      foreignColumns: [staffInCore.id],
      name: 'changes_approved_by_fkey',
    }),
    unique('changes_code_key').on(table.code),
  ],
);

export const oncallShiftsInOps = ops.table(
  'oncall_shifts',
  {
    id: serial().primaryKey().notNull(),
    staffId: uuid('staff_id').notNull(),
    startsAt: timestamp('starts_at', { withTimezone: true, mode: 'string' }).notNull(),
    endsAt: timestamp('ends_at', { withTimezone: true, mode: 'string' }).notNull(),
    role: text().default('primary').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.staffId],
      foreignColumns: [staffInCore.id],
      name: 'oncall_shifts_staff_id_fkey',
    }),
    check('oncall_shifts_check', sql`ends_at > starts_at`),
  ],
);

export const notifyChannelsInOps = ops.table(
  'notify_channels',
  {
    id: serial().primaryKey().notNull(),
    name: text().notNull(),
    kind: text().notNull(),
    targetRef: text('target_ref').notNull(),
    active: boolean().default(true).notNull(),
  },
  (table) => [unique('notify_channels_name_key').on(table.name)],
);

export const notifyRulesInOps = ops.table(
  'notify_rules',
  {
    id: serial().primaryKey().notNull(),
    channelId: integer('channel_id').notNull(),
    minSeverity: text('min_severity').default('down').notNull(),
    buildingId: uuid('building_id'),
    roleCode: text('role_code'),
    onlyUnacked: boolean('only_unacked').default(true).notNull(),
    delayMinutes: smallint('delay_minutes').default(0).notNull(),
    escalateMinutes: smallint('escalate_minutes'),
    schoolHoursOnly: boolean('school_hours_only').default(false).notNull(),
    active: boolean().default(true).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.channelId],
      foreignColumns: [notifyChannelsInOps.id],
      name: 'notify_rules_channel_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.buildingId],
      foreignColumns: [buildingsInCore.id],
      name: 'notify_rules_building_id_fkey',
    }),
    foreignKey({
      columns: [table.roleCode],
      foreignColumns: [deviceRolesInCatalog.code],
      name: 'notify_rules_role_code_fkey',
    }),
  ],
);

export const runbooksInOps = ops.table(
  'runbooks',
  {
    id: serial().primaryKey().notNull(),
    title: text().notNull(),
    url: text().notNull(),
    roleCode: text('role_code'),
    modelId: integer('model_id'),
    deviceId: uuid('device_id'),
    causeCode: text('cause_code'),
  },
  (table) => [
    foreignKey({
      columns: [table.roleCode],
      foreignColumns: [deviceRolesInCatalog.code],
      name: 'runbooks_role_code_fkey',
    }),
    foreignKey({
      columns: [table.modelId],
      foreignColumns: [modelsInCatalog.id],
      name: 'runbooks_model_id_fkey',
    }),
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'runbooks_device_id_fkey',
    }),
  ],
);

export const runsInSync = sync.table(
  'runs',
  {
    id: bigserial({ mode: 'bigint' }).primaryKey().notNull(),
    systemCode: text('system_code').notNull(),
    job: text().notNull(),
    startedAt: timestamp('started_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    finishedAt: timestamp('finished_at', { withTimezone: true, mode: 'string' }),
    status: text().default('running').notNull(),
    createdN: integer('created_n').default(0).notNull(),
    updatedN: integer('updated_n').default(0).notNull(),
    errorN: integer('error_n').default(0).notNull(),
    detail: jsonb().default({}).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.systemCode],
      foreignColumns: [sourceSystemsInCore.code],
      name: 'runs_system_code_fkey',
    }),
  ],
);

export const issuesInSync = sync.table(
  'issues',
  {
    id: bigserial({ mode: 'bigint' }).primaryKey().notNull(),
    // You can use { mode: "bigint" } if numbers are exceeding js number limitations
    runId: bigint('run_id', { mode: 'number' }),
    systemCode: text('system_code').notNull(),
    kind: text().notNull(),
    externalId: text('external_id'),
    entityTable: text('entity_table'),
    entityId: uuid('entity_id'),
    message: text().notNull(),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'string' })
      .defaultNow()
      .notNull(),
    resolvedAt: timestamp('resolved_at', { withTimezone: true, mode: 'string' }),
    resolvedBy: uuid('resolved_by'),
  },
  (table) => [
    foreignKey({
      columns: [table.runId],
      foreignColumns: [runsInSync.id],
      name: 'issues_run_id_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.systemCode],
      foreignColumns: [sourceSystemsInCore.code],
      name: 'issues_system_code_fkey',
    }),
    foreignKey({
      columns: [table.resolvedBy],
      foreignColumns: [usersInAuth.id],
      name: 'issues_resolved_by_fkey',
    }),
  ],
);

export const floorsInCore = core.table(
  'floors',
  {
    id: uuid().defaultRandom().primaryKey().notNull(),
    buildingId: uuid('building_id').notNull(),
    level: smallint().notNull(),
    name: text(),
  },
  (table) => [
    foreignKey({
      columns: [table.buildingId],
      foreignColumns: [buildingsInCore.id],
      name: 'floors_building_id_fkey',
    }).onDelete('cascade'),
    unique('floors_building_id_level_key').on(table.buildingId, table.level),
  ],
);

export const modelsInCatalog = catalog.table(
  'models',
  {
    id: serial().primaryKey().notNull(),
    vendorOrgId: uuid('vendor_org_id'),
    name: text().notNull(),
    kind: text().notNull(),
    portCount: smallint('port_count'),
    poeBudgetW: smallint('poe_budget_w'),
    eolDate: date('eol_date'),
    datasheetUrl: text('datasheet_url'),
    specs: jsonb().default({}).notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.vendorOrgId],
      foreignColumns: [organizationsInCore.id],
      name: 'models_vendor_org_id_fkey',
    }),
    unique('models_vendor_org_id_name_key').on(table.vendorOrgId, table.name),
  ],
);

export const changeLogInAudit = audit.table(
  'change_log',
  {
    id: bigserial({ mode: 'bigint' }).primaryKey().notNull(),
    at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    actor: text()
      .default(sql`COALESCE(current_setting('app.actor'::text, true), (CURRENT_USER)::text)`)
      .notNull(),
    tableName: text('table_name').notNull(),
    rowId: text('row_id').notNull(),
    op: text().notNull(),
    before: jsonb(),
    after: jsonb(),
  },
  (table) => [
    index('change_log_row').using(
      'btree',
      table.tableName.asc().nullsLast().op('text_ops'),
      table.rowId.asc().nullsLast().op('timestamptz_ops'),
      table.at.desc().nullsFirst().op('text_ops'),
    ),
  ],
);

export const userActionsInAudit = audit.table(
  'user_actions',
  {
    id: bigserial({ mode: 'bigint' }).primaryKey().notNull(),
    at: timestamp({ withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    userId: uuid('user_id'),
    apiClientId: uuid('api_client_id'),
    action: text().notNull(),
    target: text(),
    detail: jsonb().default({}).notNull(),
    sourceIp: inet('source_ip'),
  },
  (table) => [
    index('user_actions_time').using('btree', table.at.desc().nullsFirst().op('timestamptz_ops')),
    foreignKey({
      columns: [table.userId],
      foreignColumns: [usersInAuth.id],
      name: 'user_actions_user_id_fkey',
    }),
    foreignKey({
      columns: [table.apiClientId],
      foreignColumns: [apiClientsInAuth.id],
      name: 'user_actions_api_client_id_fkey',
    }),
  ],
);

export const deviceVlansInNet = net.table(
  'device_vlans',
  {
    deviceId: uuid('device_id').notNull(),
    vlanId: integer('vlan_id').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'device_vlans_device_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.vlanId],
      foreignColumns: [vlansInNet.id],
      name: 'device_vlans_vlan_id_fkey',
    }),
    primaryKey({ columns: [table.deviceId, table.vlanId], name: 'device_vlans_pkey' }),
  ],
);

export const entityTagsInCore = core.table(
  'entity_tags',
  {
    entityTable: text('entity_table').notNull(),
    entityId: uuid('entity_id').notNull(),
    tagId: integer('tag_id').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.tagId],
      foreignColumns: [tagsInCore.id],
      name: 'entity_tags_tag_id_fkey',
    }).onDelete('cascade'),
    primaryKey({
      columns: [table.entityTable, table.entityId, table.tagId],
      name: 'entity_tags_pkey',
    }),
  ],
);

export const interfaceVlansInNet = net.table(
  'interface_vlans',
  {
    interfaceId: uuid('interface_id').notNull(),
    vlanId: integer('vlan_id').notNull(),
    mode: text().notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.interfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'interface_vlans_interface_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.vlanId],
      foreignColumns: [vlansInNet.id],
      name: 'interface_vlans_vlan_id_fkey',
    }),
    primaryKey({ columns: [table.interfaceId, table.vlanId], name: 'interface_vlans_pkey' }),
    check(
      'interface_vlans_mode_check',
      sql`mode = ANY (ARRAY['access'::text, 'tagged'::text, 'native'::text])`,
    ),
  ],
);

export const userRolesInAuth = auth.table(
  'user_roles',
  {
    userId: uuid('user_id').notNull(),
    roleCode: text('role_code').notNull(),
    scopeBuildingId: uuid('scope_building_id'),
  },
  (table) => [
    foreignKey({
      columns: [table.userId],
      foreignColumns: [usersInAuth.id],
      name: 'user_roles_user_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.roleCode],
      foreignColumns: [rolesInAuth.code],
      name: 'user_roles_role_code_fkey',
    }),
    foreignKey({
      columns: [table.scopeBuildingId],
      foreignColumns: [buildingsInCore.id],
      name: 'user_roles_scope_building_id_fkey',
    }),
    primaryKey({ columns: [table.userId, table.roleCode], name: 'user_roles_pkey' }),
  ],
);

export const changeItemsInOps = ops.table(
  'change_items',
  {
    changeId: uuid('change_id').notNull(),
    entityTable: text('entity_table').notNull(),
    entityId: uuid('entity_id').notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.changeId],
      foreignColumns: [changesInOps.id],
      name: 'change_items_change_id_fkey',
    }).onDelete('cascade'),
    primaryKey({
      columns: [table.changeId, table.entityTable, table.entityId],
      name: 'change_items_pkey',
    }),
  ],
);

export const locationMetricsInCore = core.table(
  'location_metrics',
  {
    locationId: uuid('location_id').notNull(),
    metric: text().notNull(),
    value: numeric().notNull(),
    source: text().notNull(),
    asOf: timestamp('as_of', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
  },
  (table) => [
    foreignKey({
      columns: [table.locationId],
      foreignColumns: [locationsInCore.id],
      name: 'location_metrics_location_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.source],
      foreignColumns: [sourceSystemsInCore.code],
      name: 'location_metrics_source_fkey',
    }),
    primaryKey({
      columns: [table.locationId, table.metric, table.source],
      name: 'location_metrics_pkey',
    }),
  ],
);

export const availabilityMonthlyInOps = ops.table(
  'availability_monthly',
  {
    deviceId: uuid('device_id').notNull(),
    month: date().notNull(),
    uptimePct: numeric('uptime_pct', { precision: 6, scale: 3 }).notNull(),
    downtimeMinutes: integer('downtime_minutes').default(0).notNull(),
    incidentCount: integer('incident_count').default(0).notNull(),
    schoolHoursUptimePct: numeric('school_hours_uptime_pct', { precision: 6, scale: 3 }),
  },
  (table) => [
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'availability_monthly_device_id_fkey',
    }).onDelete('cascade'),
    primaryKey({ columns: [table.deviceId, table.month], name: 'availability_monthly_pkey' }),
  ],
);

export const cableCoresInNet = net.table(
  'cable_cores',
  {
    cableId: uuid('cable_id').notNull(),
    coreNo: smallint('core_no').notNull(),
    color: text(),
    status: text().default('spare').notNull(),
    aInterfaceId: uuid('a_interface_id'),
    bInterfaceId: uuid('b_interface_id'),
    lossDb: numeric('loss_db', { precision: 5, scale: 2 }),
    testedAt: date('tested_at'),
  },
  (table) => [
    foreignKey({
      columns: [table.cableId],
      foreignColumns: [cablesInNet.id],
      name: 'cable_cores_cable_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.aInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'cable_cores_a_interface_id_fkey',
    }).onDelete('set null'),
    foreignKey({
      columns: [table.bInterfaceId],
      foreignColumns: [interfacesInNet.id],
      name: 'cable_cores_b_interface_id_fkey',
    }).onDelete('set null'),
    primaryKey({ columns: [table.cableId, table.coreNo], name: 'cable_cores_pkey' }),
  ],
);

export const discoveredNeighborsInSync = sync.table(
  'discovered_neighbors',
  {
    deviceId: uuid('device_id').notNull(),
    localInterface: text('local_interface').notNull(),
    remoteSysname: text('remote_sysname'),
    remotePort: text('remote_port'),
    remoteMac: macaddr('remote_mac'),
    remoteIp: inet('remote_ip'),
    protocol: text().notNull(),
    seenAt: timestamp('seen_at', { withTimezone: true, mode: 'string' }).defaultNow().notNull(),
    matchedLinkId: uuid('matched_link_id'),
  },
  (table) => [
    foreignKey({
      columns: [table.deviceId],
      foreignColumns: [devicesInNet.id],
      name: 'discovered_neighbors_device_id_fkey',
    }).onDelete('cascade'),
    foreignKey({
      columns: [table.matchedLinkId],
      foreignColumns: [linksInNet.id],
      name: 'discovered_neighbors_matched_link_id_fkey',
    }).onDelete('set null'),
    primaryKey({
      columns: [table.deviceId, table.localInterface, table.protocol],
      name: 'discovered_neighbors_pkey',
    }),
  ],
);
export const vLocationsInApi = api
  .view('v_locations', {
    locCode: text('loc_code'),
    roomNumber: text('room_number'),
    buildingCode: text('building_code'),
    buildingName: text('building_name'),
    floor: smallint(),
    name: text(),
    typeCode: text('type_code'),
    corridorOrder: smallint('corridor_order'),
    side: text(),
    hasRack: boolean('has_rack'),
    ownerSystem: text('owner_system'),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }),
  })
  .as(
    sql`SELECT l.loc_code, l.room_number, b.code AS building_code, b.name AS building_name, f.level AS floor, l.name, l.type_code, l.corridor_order, l.side, l.has_rack, l.owner_system, l.verified_at FROM core.locations l JOIN core.floors f ON f.id = l.floor_id JOIN core.buildings b ON b.id = f.building_id WHERE l.deleted_at IS NULL`,
  );

export const vDevicesInApi = api
  .view('v_devices', {
    code: text(),
    displayName: text('display_name'),
    hostname: text(),
    roleCode: text('role_code'),
    layer: text(),
    model: text(),
    mgmtIp: inet('mgmt_ip'),
    firmwareVersion: text('firmware_version'),
    buildingCode: text('building_code'),
    floor: smallint(),
    locCode: text('loc_code'),
    rackCode: text('rack_code'),
    rackUStart: smallint('rack_u_start'),
    uplinkCode: text('uplink_code'),
    uplinkMedia: text('uplink_media'),
    managedByCode: text('managed_by_code'),
    powerSourceCode: text('power_source_code'),
    zabbixHostid: text('zabbix_hostid'),
    glpiId: text('glpi_id'),
    assetTag: text('asset_tag'),
    warrantyUntil: date('warranty_until'),
    eolDate: date('eol_date'),
    lifecycle: text(),
    dataStatus: text('data_status'),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }),
  })
  .as(
    sql`SELECT d.code, d.display_name, d.hostname, d.role_code, r.layer, m.name AS model, d.mgmt_ip, d.firmware_version, b.code AS building_code, COALESCE(f.level, lf.level) AS floor, l.loc_code, rk.code AS rack_code, d.rack_u_start, up.code AS uplink_code, lk.media_code AS uplink_media, mg.code AS managed_by_code, ps.code AS power_source_code, zx.external_id AS zabbix_hostid, gl.external_id AS glpi_id, a.asset_tag, a.warranty_until, m.eol_date, d.lifecycle, d.data_status, d.verified_at FROM net.devices d JOIN catalog.device_roles r ON r.code = d.role_code LEFT JOIN catalog.models m ON m.id = d.model_id LEFT JOIN core.locations l ON l.id = d.location_id LEFT JOIN core.floors lf ON lf.id = l.floor_id LEFT JOIN core.floors f ON f.id = d.floor_id LEFT JOIN core.buildings b ON b.id = COALESCE(f.building_id, lf.building_id) LEFT JOIN net.racks rk ON rk.id = d.rack_id LEFT JOIN net.links lk ON lk.b_device_id = d.id AND lk.is_uplink AND lk.deleted_at IS NULL LEFT JOIN net.devices up ON up.id = lk.a_device_id LEFT JOIN net.devices mg ON mg.id = d.managed_by_device_id LEFT JOIN net.devices ps ON ps.id = d.power_source_device_id LEFT JOIN asset.assets a ON a.id = d.asset_id LEFT JOIN core.external_refs zx ON zx.entity_table = 'net.devices'::text AND zx.entity_id = d.id AND zx.system_code = 'zabbix'::text LEFT JOIN core.external_refs gl ON gl.entity_table = 'net.devices'::text AND gl.entity_id = d.id AND gl.system_code = 'glpi'::text WHERE d.deleted_at IS NULL`,
  );

export const vFiberCoresInApi = api
  .view('v_fiber_cores', {
    cableCode: text('cable_code'),
    kind: text(),
    coreCount: smallint('core_count'),
    coreNo: smallint('core_no'),
    color: text(),
    status: text(),
    lossDb: numeric('loss_db', { precision: 5, scale: 2 }),
    testedAt: date('tested_at'),
    aDevice: text('a_device'),
    aPort: text('a_port'),
    bDevice: text('b_device'),
    bPort: text('b_port'),
  })
  .as(
    sql`SELECT c.code AS cable_code, c.kind, c.core_count, cc.core_no, cc.color, cc.status, cc.loss_db, cc.tested_at, da.code AS a_device, ia.name AS a_port, db.code AS b_device, ib.name AS b_port FROM net.cables c JOIN net.cable_cores cc ON cc.cable_id = c.id LEFT JOIN net.interfaces ia ON ia.id = cc.a_interface_id LEFT JOIN net.devices da ON da.id = ia.device_id LEFT JOIN net.interfaces ib ON ib.id = cc.b_interface_id LEFT JOIN net.devices db ON db.id = ib.device_id WHERE c.deleted_at IS NULL AND c.kind ~~ 'fiber%'::text`,
  );

export const vOutletsInApi = api
  .view('v_outlets', {
    code: text(),
    locCode: text('loc_code'),
    locationName: text('location_name'),
    purpose: text(),
    status: text(),
    switchCode: text('switch_code'),
    switchPort: text('switch_port'),
    verifiedAt: timestamp('verified_at', { withTimezone: true, mode: 'string' }),
  })
  .as(
    sql`SELECT o.code, l.loc_code, l.name AS location_name, o.purpose, o.status, sd.code AS switch_code, si.name AS switch_port, o.verified_at FROM net.outlets o JOIN core.locations l ON l.id = o.location_id LEFT JOIN net.interfaces si ON si.id = o.switch_interface_id LEFT JOIN net.devices sd ON sd.id = si.device_id`,
  );

export const vIncidentsInApi = api
  .view('v_incidents', {
    startedAt: timestamp('started_at', { withTimezone: true, mode: 'string' }),
    endedAt: timestamp('ended_at', { withTimezone: true, mode: 'string' }),
    severity: text(),
    summary: text(),
    deviceCode: text('device_code'),
    rootDeviceCode: text('root_device_code'),
    affectedCount: integer('affected_count'),
    ackedBy: text('acked_by'),
    causeCode: text('cause_code'),
    inSchoolHours: boolean('in_school_hours'),
    glpiTicketId: text('glpi_ticket_id'),
  })
  .as(
    sql`SELECT i.started_at, i.ended_at, i.severity, i.summary, d.code AS device_code, rd.code AS root_device_code, i.affected_count, s.staff_code AS acked_by, i.cause_code, i.in_school_hours, i.glpi_ticket_id FROM ops.incidents i LEFT JOIN net.devices d ON d.id = i.device_id LEFT JOIN net.devices rd ON rd.id = i.root_device_id LEFT JOIN core.staff s ON s.id = i.acked_by`,
  );
