// Regenerates src/schema/{schema,relations}.ts from a database migrated with migrations/*.sql.
// Usage: DATABASE_URL=postgres://.../scratch_db pnpm --filter @sbc-noc/db db:pull
import { execFileSync } from 'node:child_process';
import { readFileSync, rmSync, writeFileSync } from 'node:fs';

const OUT = 'drizzle-pull';
const HEADER =
  '// GENERATED by `pnpm db:pull` (drizzle-kit pull) from a database migrated with migrations/*.sql.\n' +
  '// Do not edit by hand — change the SQL migration, migrate a scratch DB, then re-run db:pull (ADR-0018).\n';

if (!process.env.DATABASE_URL) {
  console.error('DATABASE_URL is not set');
  process.exit(1);
}

rmSync(OUT, { recursive: true, force: true });
execFileSync('drizzle-kit', ['pull'], { stdio: 'inherit' });

for (const name of ['schema', 'relations']) {
  let src = readFileSync(`${OUT}/${name}.ts`, 'utf8');
  // NodeNext needs explicit extensions.
  src = src.replace(/from "\.\/schema"/g, 'from "./schema.js"');
  // drizzle-kit renders `DEFAULT '{}'` on text[] as [""]; keep the real SQL default.
  src = src.replace(/\.default\(\[""\]\)/g, ".default(sql`'{}'`)");
  // drizzle-kit emits SQL expression defaults unquoted, e.g. .default(COALESCE(...)); wrap them in sql``.
  src = src.replace(
    /\.default\(([A-Z][A-Z_]*\(.*\))\)(?=(\.notNull\(\))?,\s*$)/gm,
    (_m, expr) => `.default(sql\`${expr.replace(/\\'/g, "'")}\`)`,
  );
  writeFileSync(`src/schema/${name}.ts`, HEADER + src);
}
rmSync(OUT, { recursive: true, force: true });
execFileSync('prettier', ['--write', 'src/schema'], { stdio: 'inherit' });
